[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

fs_permissions = [
{ access = 'read-write', path = './json' },
{ access = 'read', path = './out' },
]

[fuzz]
runs=2

[etherscan]
arbitrum = { key = "I3IKFP5UESHAVK5B4WKAYY772BCNPICE15" }
